/*
 Quantcast measurement tag
 Copyright (c) 2008-2022, Quantcast Corp.
*/
'use strict';(function(a,m,h){var n=function(d){var e=h.createElement("a");e.href=d;return e},p=[/^http[s]?:\/\/((adservice.google.*)|([^\/]*fls\.doubleclick\.net))\/.*~oref=(?<url>[^;\n]*)/,/^http[s]?:\/\/[^\/]*tealium.*\/.*page_url=(?<url>[^&]*)/],q=function(d,e,f){return d?"nc"===d?!e||!f||0>e.indexOf(f):"eq"===d?e===f:"sw"===d?0===e.indexOf(f):"ew"===d?(d=e.length-f.length,e=e.lastIndexOf(f,d),-1!==e&&e===d):"c"===d?0<=e.indexOf(f):!1:!1},b=function(d,e,f){if(m.top!==m.self){try{for(var k=0;k<
p.length;k++){var l=h.location.href.match(p[k]);if(l&&l.groups.url){var g=decodeURIComponent(l.groups.url);break}}}catch(r){}g=g?n(g):n(h.referrer)}else g=h.location;g=g.href;q(e,g,f)?d(g):d(!1)},c=function(d){return"array"==={}.toString.call(d).match(/\s([a-zA-Z]+)/)[1].toLowerCase()?{labels:d.join(",")}:{labels:""+d}};__qc.apply(null,["rules",[a,null,[[c,"Category.TCG"]],[[b,"c","hearthhead.com"]]],[a,null,[[c,"Category.MMO.RPG"]],[[b,"c","wowhead.com"]]],[a,null,[[c,"Category.MMO.RPG"]],[[b,"c",
"wowinterface.com"]]],[a,null,[[c,"Category.MMO.RPG"]],[[b,"c","dayzdb.com"]]],[a,null,[[c,"Category.MMO.RPG"]],[[b,"c","xivdb.com"]]],[a,null,[[c,"Category.MMO.RPG"]],[[b,"c","esohead.com"]]],[a,null,[[c,"Category.MMO.RPG"]],[[b,"c","thottbot.com"]]],[a,null,[[c,"Category.MMO.RPG"]],[[b,"c","eq2interface.com"]]],[a,null,[[c,"Category.MMO.RPG"]],[[b,"c","lotrointerface.com"]]],[a,null,[[c,"Category.MMO.RPG"]],[[b,"c","eqinterface.com"]]],[a,null,[[c,"Category.MMO.RPG"]],[[b,"c","mmointerface.com"]]],
[a,null,[[c,"Category.MMO.RPG"]],[[b,"c","esoui.com"]]],[a,null,[[c,"Category.MMO.RPG"]],[[b,"c","riftui.com"]]],[a,null,[[c,"Category.MMO.RPG"]],[[b,"c","swtorui.com"]]],[a,null,[[c,"Category.MMO.Other"]],[[b,"c","destinydb.com"]]],[a,null,[[c,"Category.MMO.Other"]],[[b,"c","noobmeter.com"]]],[a,null,[[c,"Category.MOBA"]],[[b,"c","lolking.net"]]],[a,null,[[c,"Category.MOBA"]],[[b,"c","heroking.net"]]],[a,null,[[c,"Category.Shooter"]],[[b,"c","destinydb.com"]]],[a,null,[[c,"Category.Shooter"]],[[b,
"c","dayzdb.com"]]],[a,null,[[c,"Category.Shooter"]],[[b,"c","tf2outpost.com"]]],[a,null,[[c,"Category.Shooter"]],[[b,"c","overking.com"]]],[a,null,[[c,"Category.UI"]],[[b,"c","wowinterface.com"]]],[a,null,[[c,"Category.UI"]],[[b,"c","eq2interface.com"]]],[a,null,[[c,"Category.UI"]],[[b,"c","mmoui.com"]]],[a,null,[[c,"Category.UI"]],[[b,"c","lotrointerface.com"]]],[a,null,[[c,"Category.UI"]],[[b,"c","eqinterface.com"]]],[a,null,[[c,"Category.UI"]],[[b,"c","mmointerface.com"]]],[a,null,[[c,"Category.UI"]],
[[b,"c","esoui.com"]]],[a,null,[[c,"Category.UI"]],[[b,"c","riftui.com"]]],[a,null,[[c,"Category.UI"]],[[b,"c","swtorui.com"]]],[a,null,[[c,"Category.F2P"]],[[b,"c","lolking.net"]]],[a,null,[[c,"Category.F2P"]],[[b,"c","hearthhead.com"]]],[a,null,[[c,"Category.F2P"]],[[b,"c","noobmeter.com"]]],[a,null,[[c,"Category.F2P"]],[[b,"c","tf2outpost.com"]]],[a,null,[[c,"Category.F2P"]],[[b,"c","dotaoutpost.com"]]],[a,null,[[c,"Category.F2P"]],[[b,"c","heroking.net"]]],[a,null,[[c,"Category.RPG"]],[[b,"c",
"wowhead.com"]]],[a,null,[[c,"Category.RPG"]],[[b,"c","dayzdb.com"]]],[a,null,[[c,"Category.RPG"]],[[b,"c","xivdb.com"]]],[a,null,[[c,"Category.RPG"]],[[b,"c","esohead.com"]]],[a,null,[[c,"Category.RPG"]],[[b,"c","eq2interface.com"]]],[a,null,[[c,"Category.RPG"]],[[b,"c","lotrointerface.com"]]],[a,null,[[c,"Category.RPG"]],[[b,"c","cwmods.com"]]],[a,null,[[c,"Category.MMO.Other"]],[[b,"c","mmoui.com"]]],[a,null,[[c,"Category.MOBA"]],[[b,"c","dotaoutpost.com"]]],[a,null,[[c,"Sites.Lolking"]],[[b,"c",
"lolking.net"]]],[a,null,[[c,"Sites.Wowhead"]],[[b,"c","wowhead.com"]]],[a,null,[[c,"Sites.Destinydb"]],[[b,"c","destinydb.com"]]],[a,null,[[c,"Sites.Hearthhead.com"]],[[b,"c","hearthhead.com"]]],[a,null,[[c,"Sites.Noobmeter"]],[[b,"c","noobmeter.com"]]],[a,null,[[c,"Sites.Wowinterface"]],[[b,"c","wowinterface.com"]]],[a,null,[[c,"Sites.Zam"]],[[b,"c","zam.com"]]],[a,null,[[c,"Sites.Dayzdb"]],[[b,"c","dayzdb.com"]]],[a,null,[[c,"Sites.Xivdb"]],[[b,"c","xivdb.com"]]],[a,null,[[c,"Sites.Tf2outpost"]],
[[b,"c","tf2outpost.com"]]],[a,null,[[c,"Sites.Esohead"]],[[b,"c","esohead.com"]]],[a,null,[[c,"Sites.Allakhazam"]],[[b,"c","allakhazam.com"]]],[a,null,[[c,"Sites.Esoui"]],[[b,"c","esoui.com"]]],[a,null,[[c,"Sites.Thottbot"]],[[b,"c","thottbot.com"]]],[a,null,[[c,"Sites.Eq2interface"]],[[b,"c","eq2interface.com"]]],[a,null,[[c,"Sites.Mmoui"]],[[b,"c","mmoui.com"]]],[a,null,[[c,"Sites.Lotrointerface"]],[[b,"c","lotrointerface.com"]]],[a,null,[[c,"Sites.Overking"]],[[b,"c","overking.com"]]],[a,null,
[[c,"Sites.Dotaoutpost"]],[[b,"c","dotaoutpost.com"]]],[a,null,[[c,"Sites.Cwmods"]],[[b,"c","cwmods.com"]]],[a,null,[[c,"Sites.Heroking"]],[[b,"c","heroking.net"]]],[a,null,[[c,"Sites.Eqinterface"]],[[b,"c","eqinterface.com"]]],[a,null,[[c,"Sites.Mmointerface"]],[[b,"c","mmointerface.com"]]],[a,null,[[c,"Sites.Esoui"]],[[b,"c","esoui.com"]]],[a,null,[[c,"Sites.Riftui"]],[[b,"c","riftui.com"]]],[a,null,[[c,"Sites.Swtorui"]],[[b,"c","swtorui.com"]]]])})("p-80xBzMhbKolFI",window,document);